apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  lables:
      app: myapp
      type: front-end
spec:
  template:
    metadata:
      name: app-pod
        leblel:
          app: myapp
    spec:
      containers:
        - name: nginx-dkt-container
          image: nginx
  replicator: 3
  selector:
    matchLabels:
      type: front-end