apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
      app: myapp
      type: fron-end

spec:
  template:
     metadata:
        name: app-pod
        leblel:
           app: myapp
           type: front-end
     spec:
       containers:
         - name: nginx-dkt-container
           image: nginx
  replicas: 3